// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo5J435I7LzAlwX55lLAutmQwabULtxK8',
    appId: '1:518829172013:web:04188713306e41dac7dfa4',
    messagingSenderId: '518829172013',
    projectId: 'flutter-bloc-loin-photolibrary',
    authDomain: 'flutter-bloc-loin-photolibrary.firebaseapp.com',
    storageBucket: 'flutter-bloc-loin-photolibrary.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFp4JycfcVcuUjrntAP74MxTMjRtmzRDc',
    appId: '1:518829172013:android:3517a0c74b79e566c7dfa4',
    messagingSenderId: '518829172013',
    projectId: 'flutter-bloc-loin-photolibrary',
    storageBucket: 'flutter-bloc-loin-photolibrary.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaLe1FxC_E5SDSVKnZvGJhkfnBolJk7Nc',
    appId: '1:518829172013:ios:f462b6d3e013d6a4c7dfa4',
    messagingSenderId: '518829172013',
    projectId: 'flutter-bloc-loin-photolibrary',
    storageBucket: 'flutter-bloc-loin-photolibrary.appspot.com',
    iosBundleId: 'com.example.loginFirebaseBlocExample',
  );
}
